apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 92.2.0
      helm:
        valueFiles:
          - $values/platform/monitoring/kube-prometheus-stack.values.yaml
    - repoURL: https://github.com/mrnobodyone/gitops-config.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/mrnobodyone/gitops-config.git
      targetRevision: main
      path: platform/monitoring/extras
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff: {duration: 20s, factor: 2, maxDuration: 3m}
